openapi: "3.0.1"
info:
  title: "Botio Live Chat API"
  description: "This is an API for Botio livechat system."
  version: "1.0.0"
  contact:
    email: "admin@botio.io"
servers:
  # id is subject to change
  - url: "https://{id}.execute-api.ap-southeast-1.amazonaws.com/{stage}"
    variables:
      id:
        default: "1ai1vqnymh"
      stage:
        default: "dev"
tags:
  - name: facebook
    description: "Operations that involve facebook platform"
  - name: instagram
    description: "Operations that involve instagram platform"
  - name: line
    description: "Operations that involve line platform"
  - name: all
    description: "Operations that involve all platforms"
  - name: shop
    description: "Operations that involve shop meta information"
  - name: root
    description: "Top-level operations"
paths:
  # /{shop_id}/facebook/...
  /shops/{shop_id}/facebook/{page_id}/webhook:
    get:
      tags:
        - facebook
      summary: Facebook webhook verification
      description: |
        For use by facebook to verify a webhook endpoint.
      operationId: verifyFacebookWebhook
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
      responses:
        "200":
          description: "OK: Webhook handler is up and running."
        "400":
          description: "Bad Request: Check path parameters."
        "404":
          description: "Not Found: Page not found."
        "500":
          description: "Internal Server Error"
    post:
      tags:
        - facebook
      summary: Facebook webhook events
      description: |
        For use by facebook to send webhook events.
      operationId: facebookWebhook
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
      responses:
        "200":
          description: "OK: Webhook events received."
        "400":
          description: "Bad Request: Check path parameters."
        "401":
          description: "Unauthorized: Invalid signature."
        "404":
          description: "Not Found: Page not found."
        "500":
          description: "Internal Server Error"
  /shops/{shop_id}/facebook/{page_id}/conversations/{conversation_id}:
    get:
      tags:
        - facebook
      summary: Get a facebook conversation
      operationId: getFacebookConversation
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
        - $ref: "#/components/parameters/ConversationID"
      responses:
        "200":
          description: "OK: Conversation found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversationWrapper"
        "400":
          description: "Bad request: Check path parameters."
        "404":
          description: "Not Found: Conversation not found."
        "500":
          description: "Internal Server Error"
    patch:
      tags:
        - facebook
      summary: Update a facebook conversation's field(s)
      operationId: patchFacebookConversation
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
        - $ref: "#/components/parameters/ConversationID"
      requestBody:
        $ref: "#/components/requestBodies/PatchConversation"
      responses:
        "200":
          description: "OK: Conversation updated."
        "400":
          description: "Bad request: Check path parameters and request body."
        "404":
          description: "Not Found: Conversation not found."
        "500":
          description: "Internal Server Error"
  /shops/{shop_id}/facebook/{page_id}/conversations:
    get:
      tags:
        - facebook
      summary: List a facebook page's conversations
      operationId: listFacebookPageConversations
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
        - $ref: "#/components/parameters/Skip"
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/ListConversationsFilter"
      responses:
        "200":
          description: "OK: Conversations found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversationArray"
        "204":
          description: "No Content: No conversations found"
        "400":
          description: "Bad Request: Check path parameters and query string parameters."
        "404":
          description: "Not Found: Page not found."
        "500":
          description: "Internal Server Error"
  /shops/{shop_id}/facebook/{page_id}/conversations/{conversation_id}/messages:
    get:
      tags:
        - facebook
      summary: List a facebook conversation's messages
      operationId: listFacebookConversationMessages
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
        - $ref: "#/components/parameters/ConversationID"
        - $ref: "#/components/parameters/Skip"
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/ListMessagesFilter"
      responses:
        "200":
          description: "OK: Messages found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageArray"
        "204":
          description: "No Content: No messages found"
        "400":
          description: "Bad Request: Check path parameters and query string parameters."
        "404":
          description: "Not Found: Conversation not found."
        "500":
          description: "Internal Server Error"
    post:
      tags:
        - facebook
      summary: Send a message to a facebook conversation
      operationId: postFacebookMessage
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
        - $ref: "#/components/parameters/ConversationID"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  required:
                    - message
                  properties:
                    message:
                      type: string
                - type: object
                  required:
                    - attachment
                  properties:
                    attachment:
                      type: object
                      required:
                        - type
                        - payload
                      properties:
                        type:
                          type: string
                          enum:
                            - "image"
                            - "video"
                            - "audio"
                            - "file"
                            - "facebook-template-generic"
                        payload:
                          oneOf:
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadImage"
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadVideo"
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadAudio"
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadFile"
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadFacebookTemplateGeneric"
            examples:
              text:
                value:
                  message: "Hello, world!"
              image:
                value:
                  attachment:
                    type: "image"
                    payload:
                      src: "https://example.com/image.jpg"
              video:
                value:
                  attachment:
                    type: "video"
                    payload:
                      src: "https://example.com/video.mp4"
              audio:
                value:
                  attachment:
                    type: "audio"
                    payload:
                      src: "https://example.com/audio.mp3"
              file:
                value:
                  attachment:
                    type: "file"
                    payload:
                      src: "https://example.com/file.pdf"
              facebook template generic:
                value:
                  attachment:
                    type: "facebook-template-generic"
                    payload:
                      fb_template_generic:
                        title: "Your wishlist"
                        message: "Take a look at these great deals!"
                        picture: "https://example.com/image.jpg"
                        buttons:
                          - url: "https://example.com/product/1"
                            title: "View Product"
                          - url: "https://example.com/product/2"
                            title: "View Product"

              
      responses:
        "200":
          description: "OK: Message sent"
        "400":
          description: "Bad Request: Check path parameters and request body."
        "404":
          description: "Not Found: Conversation not found."
        "500":
          description: "Internal Server Error"
  /shops/{shop_id}/facebook/{page_id}:
    get:
      tags:
        - facebook
      summary: Get a facebook page's conversations status
      description: |
        Get a facebook page's unread and all conversations counts.
      operationId: getFacebookPageConversationStatus
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
      responses:
        "200":
          description: "OK: Page's conversation status found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageConversationStatus"
        "400":
          description: "Bad Request: Check path parameters."
        "404":
          description: "Not Found: Page not found."
        "500":
          description: "Internal Server Error"
  # /{shop_id}/instagram/...
  /shops/{shop_id}/instagram/{page_id}/webhook:
    get:
      tags:
        - instagram
      summary: Instagram webhook verification
      description: |
        For use by instagram to verify a webhook endpoint.
      operationId: verifyInstagramWebhook
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
      responses:
        "200":
          description: "OK: Webhook handler is up and running."
        "400":
          description: "Bad Request: Check path parameters."
        "404":
          description: "Not Found: Page not found."
        "500":
          description: "Internal Server Error"
    post:
      tags:
        - instagram
      summary: Instagram webhook events
      description: |
        For use by instagram to send webhook events.
      operationId: instagramWebhook
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
      responses:
        "200":
          description: "OK: Webhook events received."
        "400":
          description: "Bad Request: Check path parameters."
        "401":
          description: "Unauthorized: Invalid signature."
        "404":
          description: "Not Found: Page not found."
        "500":
          description: "Internal Server Error"
  /shops/{shop_id}/instagram/{page_id}/conversations/{conversation_id}:
    get:
      tags:
        - instagram
      summary: Get an instagram conversation
      operationId: getInstagramConversation
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
        - $ref: "#/components/parameters/ConversationID"
      responses:
        "200":
          description: "OK: Conversation found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversationWrapper"
        "400":
          description: "Bad request: Check path parameters."
        "404":
          description: "Not Found: Conversation not found."
        "500":
          description: "Internal Server Error"
    patch:
      tags:
        - instagram
      summary: Update an instagram conversation's field(s)
      operationId: patchInstagramConversation
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
        - $ref: "#/components/parameters/ConversationID"
      requestBody:
        $ref: "#/components/requestBodies/PatchConversation"
      responses:
        "200":
          description: "OK: Conversation updated."
        "400":
          description: "Bad request: Check path parameters and request body."
        "404":
          description: "Not Found: Conversation not found."
        "500":
          description: "Internal Server Error"
  /shops/{shop_id}/instagram/{page_id}/conversations:
    get:
      tags:
        - instagram
      summary: List an instagram page's conversations
      operationId: listInstagramPageConversations
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
        - $ref: "#/components/parameters/Skip"
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/ListConversationsFilter"
      responses:
        "200":
          description: "OK: Conversations found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversationArray"
        "204":
          description: "No Content: No conversations found"
        "400":
          description: "Bad Request: Check path parameters and query string parameters."
        "404":
          description: "Not Found: Page not found."
        "500":
          description: "Internal Server Error"
  /shops/{shop_id}/instagram/{page_id}/conversations/{conversation_id}/messages:
    get:
      tags:
        - instagram
      summary: List an instagram conversation's messages
      operationId: listInstagramConversationMessages
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
        - $ref: "#/components/parameters/ConversationID"
        - $ref: "#/components/parameters/Skip"
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/ListMessagesFilter"
      responses:
        "200":
          description: "OK: Messages found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageArray"
        "204":
          description: "No Content: No messages found"
        "400":
          description: "Bad Request: Check path parameters and query string parameters."
        "404":
          description: "Not Found: Conversation not found."
        "500":
          description: "Internal Server Error"
    post:
      tags:
        - instagram
      summary: Send a message to an instagram conversation
      operationId: postInstagramMessage
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
        - $ref: "#/components/parameters/ConversationID"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  required:
                    - message
                  properties:
                    message:
                      type: string
                - type: object
                  required:
                    - attachment
                  properties:
                    attachment:
                      type: object
                      required:
                        - type
                        - payload
                      properties:
                        type:
                          type: string
                          enum:
                            - "image"
                            - "video"
                            - "audio"
                            - "file"
                            - "instagram-template-generic"
                        payload:
                          oneOf:
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadImage"
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadVideo"
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadAudio"
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadFile"
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadInstagramGeneric"
            examples:
              text:
                value:
                  message: "Hello, world!"
              image:
                value:
                  attachment:
                    type: "image"
                    payload:
                      src: "https://example.com/image.jpg"
              video:
                value:
                  attachment:
                    type: "video"
                    payload:
                      src: "https://example.com/video.mp4"
              audio:
                value:
                  attachment:
                    type: "audio"
                    payload:
                      src: "https://example.com/audio.mp3"
              file:
                value:
                  attachment:
                    type: "file"
                    payload:
                      src: "https://example.com/file.pdf"
              instagram template generic:
                value:
                  attachment:
                    type: "instagram-template-generic"
                    payload:
                      ig_template_generic:
                        title: "Your wishlist"
                        message: "Take a look at these great deals!"
                        picture: "https://example.com/image.jpg"
                        buttons:
                          - url: "https://example.com/product/1"
                            title: "View Product"
                          - url: "https://example.com/product/2"
                            title: "View Product"

      responses:
        "200":
          description: "OK: Message sent"
        "400":
          description: "Bad Request: Check path parameters and request body."
        "404":
          description: "Not Found: Conversation not found."
        "500":
          description: "Internal Server Error"
  /shops/{shop_id}/instagram/{page_id}:
    get:
      tags:
        - instagram
      summary: Get an instagram page's conversations status
      description: |
        Get an instagram page's unread and all conversation counts.
      operationId: getInstagramPageConversationStatus
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
      responses:
        "200":
          description: "OK: Page's conversation status found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageConversationStatus"
        "400":
          description: "Bad Request: Check path parameters."
        "404":
          description: "Not Found: Page not found."
        "500":
          description: "Internal Server Error"
  # /{shop_id}/line/...
  /shops/{shop_id}/line/{page_id}/webhook:
    post:
      tags:
        - line
      summary: Line webhook events
      description: |
        For use by line to send webhook events.
      operationId: lineWebhook
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
      responses:
        "200":
          description: "OK: Webhook events received."
        "400":
          description: "Bad Request: Check path parameters."
        "401":
          description: "Unauthorized: Invalid signature."
        "404":
          description: "Not Found: Page not found."
        "500":
          description: "Internal Server Error"
  /shops/{shop_id}/line/{page_id}/conversations/{conversation_id}:
    get:
      tags:
        - line
      summary: Get a line conversation
      operationId: getLineConversation
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
        - $ref: "#/components/parameters/ConversationID"
      responses:
        "200":
          description: "OK: Conversation found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversationWrapper"
        "400":
          description: "Bad request: Check path parameters."
        "404":
          description: "Not Found: Conversation not found."
        "500":
          description: "Internal Server Error"
    patch:
      tags:
        - line
      summary: Update a line conversation's field(s)
      operationId: patchLineConversation
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
        - $ref: "#/components/parameters/ConversationID"
      requestBody:
        $ref: "#/components/requestBodies/PatchConversation"
      responses:
        "200":
          description: "OK: Conversation updated."
        "400":
          description: "Bad request: Check path parameters and request body."
        "404":
          description: "Not Found: Conversation not found."
        "500":
          description: "Internal Server Error"
  /shops/{shop_id}/line/{page_id}/conversations:
    get:
      tags:
        - line
      summary: List a line page's conversations
      operationId: listLinePageConversations
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
        - $ref: "#/components/parameters/Skip"
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/ListConversationsFilter"
      responses:
        "200":
          description: "OK: Conversations found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversationArray"
        "204":
          description: "No Content: No conversations found"
        "400":
          description: "Bad Request: Check path parameters and query string parameters."
        "404":
          description: "Not Found: Page not found."
        "500":
          description: "Internal Server Error"
  /shops/{shop_id}/line/{page_id}/conversations/{conversation_id}/messages:
    get:
      tags:
        - line
      summary: List a line conversation's messages
      operationId: listLineConversationMessages
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
        - $ref: "#/components/parameters/ConversationID"
        - $ref: "#/components/parameters/Skip"
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/ListMessagesFilter"
      responses:
        "200":
          description: "OK: Messages found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageArray"
        "204":
          description: "No Content: No messages found"
        "400":
          description: "Bad Request: Check path parameters and query string parameters."
        "404":
          description: "Not Found: Conversation not found."
        "500":
          description: "Internal Server Error"
    post:
      tags:
        - line
      summary: Send a message to a line conversation
      operationId: postLineMessage
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
        - $ref: "#/components/parameters/ConversationID"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  required:
                    - message
                  properties:
                    message:
                      type: string
                - type: object
                  required:
                    - attachment
                  properties:
                    attachment:
                      required:
                        - type
                        - payload
                      properties:
                        type:
                          type: string
                          enum:
                            - "image"
                            - "video"
                            - "audio"
                            - "line-template-buttons"
                            - "line-template-confirm"
                            - "line-template-carousel"
                            - "line-template-image-carousel"
                        payload:
                          oneOf:
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadImage"
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadVideo"
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadAudio"
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadLineTemplateButtons"
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadLineTemplateConfirm"
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadLineTemplateCarousel"
                            - $ref: "#/components/schemas/PostMessageAttachmentPayloadLineTemplateImageCarousel"
            examples:
              text:
                value:
                  message: "Hello, world!"
              image:
                value:
                  attachment:
                    type: "image"
                    payload:
                      src: "https://example.com/image.jpg"
              video:
                value:
                  attachment:
                    type: "video"
                    payload:
                      src: "https://example.com/video.mp4"
              audio:
                value:
                  attachment:
                    type: "audio"
                    payload:
                      src: "https://example.com/audio.mp3"
              line template buttons:
                value:
                  attachment:
                    type: "line-template-buttons"
                    payload:
                      line_template_buttons:
                        altText: "You have a new buttons template message!"
                        text: "Please select an option."
                        actions:
                          - label: "Option 1"
                            uri: "https://example.com/option1"
                          - label: "Option 2"
                            uri: "https://example.com/option2"
                          - label: "Option 3"
                            uri: "https://example.com/option3"
                          - label: "Option 4"
                            uri: "https://example.com/option4"
              line template confirm:
                value:
                  attachment:
                    type: "line-template-confirm"
                    payload:
                      line_template_confirm:
                        altText: "You have a new confirm template message!"
                        text: "Please select an option."
                        actions:
                          - label: "Yes"
                            uri: "https://example.com/yes"
                          - label: "No"
                            uri: "https://example.com/no"
              line template carousel:
                value:
                  attachment:
                    type: "line-template-carousel"
                    payload:
                      line_template_carousel:
                        altText: "You have a new carousel template message!"
                        columns:
                          - text: "Please select an option."
                            actions:
                              - label: "Option 1"
                                uri: "https://example.com/option1"
                              - label: "Option 2"
                                uri: "https://example.com/option2"
                              - label: "Option 3"
                                uri: "https://example.com/option3"
                          - text: "Please select an option."
                            actions:
                              - label: "Option 1"
                                uri: "https://example.com/option1"
                              - label: "Option 2"
                                uri: "https://example.com/option2"
                              - label: "Option 3"
                                uri: "https://example.com/option3"
                          - text: "Please select an option."
                            actions:
                              - label: "Option 1"
                                uri: "https://example.com/option1"
                              - label: "Option 2"
                                uri: "https://example.com/option2"
                              - label: "Option 3"
                                uri: "https://example.com/option3"
              line template image carousel:
                value:
                  attachment:
                    type: "line-template-image-carousel"
                    payload:
                      line_template_image_carousel:
                        altText: "You have a new image carousel template message!"
                        columns:
                          - imageUrl: "https://example.com/image1.jpg"
                            action:
                              label: "Option 1"
                              uri: "https://example.com/option1"
                          - imageUrl: "https://example.com/image2.jpg"
                            action:
                              label: "Option 2"
                              uri: "https://example.com/option2"
                          -  imageUrl: "https://example.com/image3.jpg"
                             action:
                               label: "Option 3"
                               uri: "https://example.com/option3"
      responses:
        "200":
          description: "OK: Message sent"
        "400":
          description: "Bad Request: Check path parameters and request body."
        "404":
          description: "Not Found: Conversation not found."
        "500":
          description: "Internal Server Error"
  /shops/{shop_id}/line/{page_id}:
    get:
      tags:
        - line
      summary: Get a line page's conversations status
      description: |
        Get a line page's unread and all conversations counts.
      operationId: getLinePageConversationStatus
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/PageID"
      responses:
        "200":
          description: "OK: Page's conversation status found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageConversationStatus"
        "400":
          description: "Bad Request: Check path parameters."
        "404":
          description: "Not Found: Page not found."
        "500":
          description: "Internal Server Error"
  # /shops/{shop_id}/all/...
  /shops/{shop_id}/all:
    get:
      tags:
        - all
      summary: List a shop's all platforms' conversations status.
      operationId: ListShopAllPlatformsConversationsStatus
      parameters:
        - $ref: "#/components/parameters/ShopID"
      responses:
        "200":
          description: "OK: Status found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShopPlatformsConversationsStatusArray"
        "204":
          description: "No Content: No status found."
        "400":
          description: "Bad Request: Check path parameters."
        "404":
          description: "Not Found: Shop not found."
        "500":
          description: "Internal Server Error"
  /shops/{shop_id}/all/conversations:
    get:
      tags:
        - all
      summary: List a shop's all platforms' conversations.
      operationId: listShopAllPlatformsConversations
      parameters:
        - $ref: "#/components/parameters/ShopID"
        - $ref: "#/components/parameters/Skip"
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/ListConversationsFilter"
      responses:
        "200":
          description: "OK: Conversations found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversationArray"
        "204":
          description: "No Content: No conversations found."
        "400":
          description: "Bad Request: Check path parameters and query string parameters."
        "404":
          description: "Not Found: Shop not found."
        "500":
          description: "Internal Server Error"
  # /shops/...
  /shops:
    post:
      tags:
        - shop
      summary: Create a shop
      description: |
        Create a shop  with the information provided in the request body.
        Also creates an empty shop config of the shop.
      operationId: postShop
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                facebookPageID:
                  type: string
                facebookAccessToken:
                  type: string
                instagramPageID:
                  type: string
                instagramAccessToken:
                  type: string
                linePageID:
                  type: string
                lineAccessToken:
                  type: string
                lineSecret:
                  type: string
      responses:
        "200":
          description: "OK: Shop created."
          content:
            application/json:
              schema:
                type: object
                properties:
                  shopID:
                    type: string
                    description: ID of the created shop
        "400":
          description: "Bad Request: Check request body."
        "500":
          description: "Internal Server Error"
  /shops/{shop_id}:
    get:
      tags:
        - shop
      summary: List a shop's available pages
      operationId: listShopAvailablePages
      parameters:
        - $ref: "#/components/parameters/ShopID"
      responses:
        "200":
          description: "OK: Pages found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShopAvailablePagesArray"
        "204":
          description: "No Content: No pages found."
        "400":
          description: "Bad Request: Check path parameters."
        "404":
          description: "Not Found: Shop not found."
        "500":
          description: "Internal Server Error"
    patch:
      tags:
        - shop
      summary: Update a shop's information
      operationId: patchShop
      parameters:
        - $ref: "#/components/parameters/ShopID"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                facebookPageID:
                  type: string
                facebookAccessToken:
                  type: string
                instagramPageID:
                  type: string
                instagramAccessToken:
                  type: string
                linePageID:
                  type: string
                lineAccessToken:
                  type: string
                lineSecret:
                  type: string
      responses:
        "200":
          description: "OK: Shop patched."
        "400":
          description: "Bad Request: Check path parameters and request body."
        "404":
          description: "Not Found: Shop not found."
        "500":
          description: "Internal Server Error"
  /shops/{shop_id}/config:
    get:
      tags:
        - shop
      summary: Get a shop's config
      operationId: getShopConfig
      parameters:
        - $ref: "#/components/parameters/ShopID"
      responses:
        "200":
          description: "OK: Config found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShopConfigWrapper"
        "400":
          description: "Bad Request: Check path parameters."
        "404":
          description: "Not Found: Shop not found."
        "500":
          description: "Internal Server Error"
    patch:
      deprecated: true
      tags:
        - shop
      summary: Add a new shop config template message
      description: |
        Use `POST /shops/{shop_id}/config/templates` to add a new shop config template instead.
      operationId: patchShopConfig
      parameters:
        - $ref: "#/components/parameters/ShopID"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - templatePayload
              properties:
                templatePayload:
                  type: string
            examples:
              add a new template message:
                value:
                  templatePayload:
                    "some template message payload"
      responses:
        "200":
          description: "OK: Template message added."
          content:
            application/json:
              schema:
                type: object
                required:
                  - templateID
                properties:
                  templateID:
                    type: string
                    description: ID of the created template message
        "400":
          description: "Bad Request: Check path parameters and request body."
        "404":
          description: "Not Found: Shop not found."
        "500":
          description: "Internal Server Error"
  /shops/{shop_id}/config/templates:
    post:
      tags:
        - shop
      summary: Add a new shop config template message
      operationId: postShopConfigTemplate
      parameters:
        - $ref: "#/components/parameters/ShopID"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - templatePayload
              properties:
                templatePayload:
                  type: string
            examples:
              add a new template message:
                value:
                  templatePayload:
                    "some template message payload"
      responses:
        "200":
          description: "OK: Template message added."
          content:
            application/json:
              schema:
                type: object
                required:
                  - templateID
                properties:
                  templateID:
                    type: string
                    description: ID of the created template message
        "400":
          description: "Bad Request: Check path parameters and request body."
        "404":
          description: "Not Found: Shop not found."
        "500":
          description: "Internal Server Error"
  # /...
  /upload_url:
    get:
      tags:
        - root
      summary: Get an S3 presigned upload URL
      operationId: getS3PresignedUploadURL
      parameters:
        - in: query
          name: temporary
          schema:
            type: boolean
            default: false
          required: false
      responses:
        "200":
          description: "OK: Presigned upload URL created."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PresignedURL"
        "400":
          description: "Bad Request: Check query string parameters."
        "500":
          description: "Internal Server Error"
components:
  schemas:
    Message:
      required:
        - shopID
        - platform
        - pageID
        - conversationID
        - messageID
        - timestamp
        - source
        - message
        - attachments
        - isDeleted
      type: object
      properties:
        shopID:
          type: string
        platform:
          type: string
        pageID:
          type: string
        conversationID:
          type: string
        messageID:
          type: string
        timestamp:
          type: integer
          format: int64
        source:
          $ref: "#/components/schemas/Source"
        message:
          type: string
        attachments:
          type: array
          items:
            $ref: "#/components/schemas/Attachment"
        replyTo:
          $ref: "#/components/schemas/RepliedMessage"
        isDeleted:
          type: boolean
    Source:
      required:
        - userID
        - userType
      type: object
      properties:
        userID:
          type: string
        userType:
          type: string
    Attachment:
      required:
        - attachmentType
        - payload
      type: object
      properties:
        attachmentType:
          type: string
        payload:
          $ref: "#/components/schemas/Payload"
    Payload:
      required:
        - src
      type: object
      properties:
        src:
          type: string
    RepliedMessage:
      required:
        - messageID
      type: object
      properties:
        messageID:
          type: string
    Conversation:
      required:
        - shopID
        - platform
        - pageID
        - conversationID
        - conversationPic
        - updatedTime
        - participants
        - lastActivity
        - unread
      type: object
      properties:
        shopID:
          type: string
        platform:
          type: string
        pageID:
          type: string
        conversationID:
          type: string
        conversationPic:
          $ref: "#/components/schemas/Payload"
        updatedTime:
          type: integer
          format: int64
        participants:
          type: array
          items:
            $ref: "#/components/schemas/Participant"
        lastActivity:
          type: string
        unread:
          type: integer
    Participant:
      required:
        - userID
        - username
        - profilePic
      type: object
      properties:
        userID:
          type: string
        username:
          type: string
        profilePic:
          $ref: "#/components/schemas/Payload"
    ConversationArray:
      required:
        - conversations
      type: object
      properties:
        conversations:
          type: array
          items:
            $ref: "#/components/schemas/Conversation"
    MessageArray:
      required:
        - messages
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
    ConversationWrapper:
      required:
        - conversation
      type: object
      properties:
        conversation:
          $ref: "#/components/schemas/Conversation"
    MessageWrapper:
      required:
        - message
      type: object
      properties:
        message:
          $ref: "#/components/schemas/Message"
    PageConversationStatus:
      type: object
      required:
        - unreadConversations
        - allConversations
      properties:
        unreadConversations:
          type: integer
        allConversations:
          type: integer
    # /{shop_id}/all/... data models
    ShopPlatformsConversationsStatusArray:
      type: object
      required:
        - statuses
      properties:
        statuses:
          type: array
          items:
            $ref: "#/components/schemas/PlatformConversationsStatus"
    PlatformConversationsStatus:
      type: object
      required:
        - platform
        - unreadConversations
        - allConversations
      properties:
        platform:
          type: string
        unreadConversations:
          type: integer
        allConversations:
          type: integer
    # /shops/... data models
    Shop:
      type: object
      required:
        - shopID
      properties:
        shopID:
          type: string
        facebookPageID:
          type: string
        facebookAuthentication:
          $ref: "#/components/schemas/FacebookAuthentication"
        instagramPageID:
          type: string
        instagramAuthentication:
          $ref: "#/components/schemas/InstagramAuthentication"
        linePageID:
          type: string
        lineAuthentication:
          $ref: "#/components/schemas/LineAuthentication"
    FacebookAuthentication:
      type: object
      required:
        - accessToken
      properties:
        accessToken:
          type: string
    InstagramAuthentication:
      type: object
      required:
        - accessToken
      properties:
        accessToken:
          type: string
    LineAuthentication:
      type: object
      required:
        - accessToken
        - secret
      properties:
        accessToken:
          type: string
        secret:
          type: string
    ShopWrapper:
      type: object
      required:
        - shop
      properties:
        shop:
          $ref: "#/components/schemas/Shop"
    ShopAvailablePagesArray:
      type: object
      properties:
        available_pages:
          type: array
          items:
            $ref: "#/components/schemas/PageInfo"
    PageInfo:
      type: object
      required:
        - platform_name
        - page_id
      properties:
        platform_name:
          type: string
        page_id:
          type: string
    ShopConfig:
      type: object
      required:
        - shopID
        - templates
      properties:
        shopID:
          type: string
        templates:
          type: array
          items:
            $ref: "#/components/schemas/ShopTemplate"
    ShopTemplate:
      type: object
      required:
        - id
        - payload
      properties:
        id:
          type: string
        payload:
          type: string
    ShopConfigWrapper:
      type: object
      required:
        - shopConfig
      properties:
        shopConfig:
          $ref: "#/components/schemas/ShopConfig"
    # /... data models
    PresignedURL:
      type: object
      required:
        - presignedURL
      properties:
        presignedURL:
          type: string
    # common attachment types
    PostMessageAttachmentPayloadImage:
      type: object
      required:
        - src
      properties:
        src:
          type: string
          description: "URL of the image"
    PostMessageAttachmentPayloadVideo:
      type: object
      required:
        - src
      properties:
        src:
          type: string
          description: "URL of the video"
    PostMessageAttachmentPayloadAudio:
      type: object
      required:
        - src
      properties:
        src:
          type: string
          description: "URL of the audio"
    PostMessageAttachmentPayloadFile:
      type: object
      required:
        - src
      properties:
        src:
          type: string
          description: "URL of the file"
    # line template messages
    PostMessageAttachmentPayloadLineTemplateButtons:
      type: object
      required:
        - line_template_buttons
      properties:
        line_template_buttons:
          $ref: "#/components/schemas/LineTemplateButtons"
    PostMessageAttachmentPayloadLineTemplateConfirm:
      type: object
      required:
        - line_template_confirm
      properties:
        line_template_confirm:
          $ref: "#/components/schemas/LineTemplateConfirm"
    PostMessageAttachmentPayloadLineTemplateCarousel:
      type: object
      required:
        - line_template_carousel
      properties:
        line_template_carousel:
          $ref: "#/components/schemas/LineTemplateCarousel"
    PostMessageAttachmentPayloadLineTemplateImageCarousel:
      type: object
      required:
        - line_template_image_carousel
      properties:
        line_template_image_carousel:
          $ref: "#/components/schemas/LineTemplateImageCarousel"
    LineTemplateButtons:
      type: object
      required:
        - altText
        - text
        - actions
      properties:
        altText:
          type: string
          description: |
            Text displayed in notification and chat list of the recipient  
            Max character limit: 400  

        thumbnailImageUrl:
          type: string
          description: |
            Image URL
            Max character limit: 2000
            HTTPS overTLS 1.2 or later
            JPEG or PNG
            Aspect ratio: 1:1
            Max width: 1024px
            Max file size: 10 MB
        text:
          type: string
          description: |
            Text displayed in the template  
            Max character limit: 160 (no image or title)  
            Max character limit: 60 (message with an image or title)  

        defaultAction:
          $ref: "#/components/schemas/LineTemplateAction"
        actions:
          type: array
          description: |
            Action when tapped
            Max objects: 4
          items:
            $ref: "#/components/schemas/LineTemplateAction"
    LineTemplateConfirm:
      type: object
      required:
        - altText
        - text
        - actions
      properties:
        altText:
          type: string
          description: |
            Text displayed in notification and chat list of the recipient  
            Max character limit: 400  

        text:
          type: string
          description: |
            Text displayed in the template  
            Max character limit: 240  

        actions:
          type: array
          description: |
            Action when tapped  
            2 objects only  

          items:
            $ref: "#/components/schemas/LineTemplateAction"
    LineTemplateCarousel:
      type: object
      required:
        - altText
        - columns
      properties:
        altText:
          type: string
          description: |
            Text displayed in notification and chat list of the recipient  
            Max character limit: 400  

        columns:
          type: array
          description: |
            Array of columns  
            Max objects: 10  

          items:
            $ref: "#/components/schemas/LineTemplateCarouselColumn"
    LineTemplateCarouselColumn:
      type: object
      required:
        - text
        - actions
      properties:
        thumbnailImageUrl:
          type: string
          description: |
            Image URL  
            Max character limit: 2000  
            HTTPS overTLS 1.2 or later  
            JPEG or PNG  
            Aspect ratio: 1.51:1 (width:height)  
            Max width: 1024px  
            Max file size: 10 MB  

        title:
          type: string
          description: |
            Title  
            Max character limit: 40  

        text:
          type: string
          description: |
            Message text  
            Max character limit: 120 (no image or title)  
            Max character limit: 60 (message with an image or title)  

        defaultAction:
          $ref: "#/components/schemas/LineTemplateAction"
        actions:
          type: array
          description: |
            Action when tapped  
            Max objects: 3  

          items:
            $ref: "#/components/schemas/LineTemplateAction"
    LineTemplateImageCarousel:
      type: object
      required:
        - altText
        - columns
      properties:
        altText:
          type: string
          description: |
            Text displayed in notification and chat list of the recipient  
            Max character limit: 400  

        columns:
          type: array
          description: |
            Array of columns  
            Max objects: 10  

          items:
            $ref: "#/components/schemas/LineTemplateImageCarouselColumn"
    LineTemplateImageCarouselColumn:
      type: object
      required:
        - imageUrl
        - action
      properties:
        imageUrl:
          type: string
          description: |
            Image URL  
            Max character limit: 2000  
            HTTPS overTLS 1.2 or later  
            JPEG or PNG  
            Aspect ratio: 1:1  
            Max width: 1024px  
            Max file size: 10 MB  

        action:
          $ref: "#/components/schemas/LineTemplateAction"
    LineTemplateAction:
      type: object
      required:
        - uri
      properties:
        label:
          type: string
          description: |
            Label for the action  
            Max character limit: 12 (Image carousel template)  
            Max character limit: 20 (Other than image carousel)  

        uri:
          type: string
          description: |
            URI opened when the action is performed (Max character limit: 1000)  
            http(s)://  
            line://  
            tel:  

    # facebook template messages
    PostMessageAttachmentPayloadFacebookTemplateGeneric:
      type: object
      required:
        - fb_template_generic
      properties:
        fb_template_generic:
          $ref: "#/components/schemas/FacebookTemplateGeneric"
    FacebookTemplateGeneric:
      type: object
      description: |
        Requires title and at least one of the following elements: message, picture, or buttons.  

      required:
        - title
      properties:
        title:
          type: string
        message:
          type: string
        picture:
          type: string
        buttons:
          type: array
          items:
            $ref: "#/components/schemas/FacebookButton"
        default_action:
          $ref: "#/components/schemas/FacebookDefaultAction"
    FacebookButton:
      type: object
      required:
        - url
        - title
      properties:
        url:
          type: string
        title:
          type: string
    FacebookDefaultAction:
      type: object
      required:
        - url
      properties:
        url:
          type: string
    # instagram template messages
    PostMessageAttachmentPayloadInstagramGeneric:
      type: object
      required:
        - ig_template_generic
      properties:
        ig_template_generic:
          $ref: "#/components/schemas/InstagramTemplateGeneric"
    InstagramTemplateGeneric:
      type: object
      description: |
        Requires title and at least one of the following elements: message, picture, or buttons.  

      required:
        - title
      properties:
        title:
          type: string
        message:
          type: string
        picture:
          type: string
        buttons:
          type: array
          items:
            $ref: "#/components/schemas/InstagramButton"
        default_action:
          $ref: "#/components/schemas/InstagramDefaultAction"
    InstagramButton:
      type: object
      required:
        - url
        - title
      properties:
        url:
          type: string
        title:
          type: string
    InstagramDefaultAction:
      type: object
      required:
        - url
      properties:
        url:
          type: string
  parameters:
    # path parameters
    ShopID:
      in: path
      name: shop_id
      schema:
        type: string
      required: true
    PageID:
      in: path
      name: page_id
      schema:
        type: string
      required: true
    ConversationID:
      in: path
      name: conversation_id
      schema:
        type: string
      required: true
    # query string parameters
    Skip:
      in: query
      name: skip
      schema:
        type: integer
        default: 0
      required: false
    Limit:
      in: query
      name: limit
      schema:
        type: integer
        default: infinity
      required: false
    ListMessagesFilter:
      in: query
      name: filter
      schema:
        type: object
        properties:
          with_message:
            type: string
            description: Only list messages that contain this string.
      examples:
        messages containing "hello":
          value:
            with_message: hello
      required: false
    ListConversationsFilter:
      in: query
      name: filter
      description: |
        Only one filter field can be provided at a time.  

      schema:
        type: object
        properties:
          with_participants_username:
            type: string
            description: Only list conversations that contain this username (display name).

          with_message:
            type: string
            description: Only list conversations that contain messages containing this string.
      examples:
        conversations containing user "john":
          value:
            with_participants_username: john
        conversations containing message "hello":
          value:
            with_message: hello

      required: false
  requestBodies:
    PatchConversation:
      content:
        application/json:
          schema:
            type: object
            properties:
              unread:
                type: integer
          examples:
            mark as read:
              value:
                unread: 0